### ISSUE TITLE
Activity jp.toastkid.yobidashi.main.MainActivity has leaked ServiceConnection 

### ISSUE THREAD

**Issue by toastkidjp** [toastkidjp/Yobidashi_kt#390]
```
2019-07-28 01:13:22.660 26072-26072/jp.toastkid.yobidashi.d E/ActivityThread: Activity jp.toastkid.yobidashi.main.MainActivity has leaked ServiceConnection android.media.MediaScannerConnection@fe9b5d8 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity jp.toastkid.yobidashi.main.MainActivity has leaked ServiceConnection android.media.MediaScannerConnection@fe9b5d8 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1538)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1430)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1622)
        at android.app.ContextImpl.bindService(ContextImpl.java:1574)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:697)
        at android.media.MediaScannerConnection.connect(MediaScannerConnection.java:122)
        at android.media.MediaScannerConnection.scanFile(MediaScannerConnection.java:317)
        at jp.toastkid.yobidashi.editor.EditorModule.saveToFile(EditorModule.kt:319)
        at jp.toastkid.yobidashi.editor.EditorModule.saveIfNeed(EditorModule.kt:269)
        at jp.toastkid.yobidashi.browser.BrowserFragment$override.onPause(BrowserFragment.kt:1033)
        at jp.toastkid.yobidashi.browser.BrowserFragment$override.access$dispatch(Unknown Source:279)
        at jp.toastkid.yobidashi.browser.BrowserFragment.onPause(Unknown Source:12)
        at androidx.fragment.app.Fragment.performPause(Fragment.java:2777)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:933)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2656)
        at androidx.fragment.app.FragmentManagerImpl.dispatchPause(FragmentManagerImpl.java:2626)
        at androidx.fragment.app.FragmentController.dispatchPause(FragmentController.java:279)
        at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:420)
        at android.app.Activity.performPause(Activity.java:7408)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1414)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4115)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4092)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4066)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4891)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1702)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6942)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by toastkidjp** [comment]
I think following Q&A is same bug.
https://stackoverflow.com/questions/5739140/mediascannerconnection-produces-android-app-serviceconnectionleaked
